# Generated by Django 5.0.6 on 2024-12-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBlockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('reason', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('email_id', models.CharField(max_length=20)),
                ('order_number', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('phone', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.CharField(max_length=5)),
                ('ticket', models.CharField(max_length=10000)),
                ('address', models.CharField(max_length=30, null=True)),
                ('time', models.TimeField(default='00:00:00')),
                ('blocked', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBlockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
