# Generated by Django 5.0.6 on 2024-12-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobhunter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressblocklist',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='phoneblocklist',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
