# Generated by Django 5.0.6 on 2024-12-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobhunter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='kitchen_number',
            field=models.IntegerField(default=1600),
            preserve_default=False,
        ),
    ]
