# Generated by Django 5.0.6 on 2024-12-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobhunter', '0002_operationdate_order_kitchen_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdate',
            name='counter',
            field=models.IntegerField(default=1600),
            preserve_default=False,
        ),
    ]
