# Generated by Django 5.1.4 on 2024-12-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobhunter', '0002_alter_addressblocklist_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ticket',
            field=models.CharField(max_length=10000),
        ),
    ]
