# Generated by Django 5.0.6 on 2024-12-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('email_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('order_number', models.IntegerField()),
                ('customer_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('phone', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.CharField(max_length=5)),
                ('ticket', models.CharField(max_length=1000)),
            ],
        ),
    ]
