# Generated by Django 5.0.6 on 2024-12-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobhunter', '0002_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
