# Generated by Django 5.0.6 on 2024-12-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobhunter', '0003_order_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockList',
            fields=[
                ('block_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('reason', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='email_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
