# Generated by Django 5.0.6 on 2024-12-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobhunter', '0004_addressblocklist_phoneblocklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressblocklist',
            old_name='phone',
            new_name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressblocklist',
            name='reason',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='phoneblocklist',
            name='reason',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
