# Generated by Django 5.0.6 on 2024-12-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobhunter', '0004_blocklist_order_status_alter_order_email_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBlockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('reason', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBlockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('reason', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='BlockList',
        ),
    ]
