# Generated by Django 5.0.6 on 2024-12-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobhunter', '0005_rename_phone_addressblocklist_address_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressblocklist',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='email_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
