# Generated by Django 5.1.4 on 2024-12-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobhunter', '0006_alter_addressblocklist_address_alter_order_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
